import type { Metadata } from "next";
import { Work_Sans } from 'next/font/google'
import "./globals.css";

const workSans = Work_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-work-sans',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${workSans.variable} antialiased min-h-screen bg-white`}
      >
        <div className="mx-auto max-w-7xl px-4">
          {children}
        </div>
      </body>
    </html>
  );
}
